[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nftlab_progress = "FrqzKiz9NBHdy67LQ7SVx13SFoTkHHbbwv7LJTjxyXyp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
