"use client";
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { useWallet } from '@solana/wallet-adapter-react';
import { scenarios, freshProgress, completed, canOpen, advance, passQuiz, type Progress, type Mode, type ScenarioId } from '@/lib/scenarios';
import { progressSchema } from '@/lib/validation';
import { readPending, savePending, clearPending, commitConfirmed, JOURNAL_KEY, type PendingTransaction, type TransactionObserver } from '@/lib/transaction-journal';
import { withTransactionLock } from '@/lib/transaction-lock';
import DevnetWalletStatus from './devnet-wallet-status';
import { endpoint } from './providers';
const WalletButton=dynamic(()=>import('@solana/wallet-adapter-react-ui').then(m=>m.WalletMultiButton),{ssr:false});
const stages={locked:'クイズに挑戦',ready:'発行できます',minted:'発行済み',transferred:'譲渡済み',redeemed:'体験完了'};
export default function Lab(){
 const wallet=useWallet();const [mode,setMode]=useState<Mode>('demo');const [progress,setProgress]=useState<Progress>(freshProgress);const [selected,setSelected]=useState(0);const [answers,setAnswers]=useState<number[]>([]);const [quizResult,setQuizResult]=useState<boolean|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [recipient,setRecipient]=useState('');const [ready,setReady]=useState(false);const [storage,setStorage]=useState('ブラウザに保存');const operation=useRef(false);const generation=useRef(0);
 const [pending,setPending]=useState<PendingTransaction|null>(null);const [journalReady,setJournalReady]=useState(false);const [journalError,setJournalError]=useState('');
 const chainBlocked=mode==='devnet'&&(!journalReady||!!pending||!!journalError);
 useEffect(()=>{const refresh=()=>{try{setPending(readPending(localStorage));setJournalError('');}catch{setJournalError('確認待ち取引の保存内容を読み取れません。新しい取引を停止しています。');}setJournalReady(true);};refresh();const changed=(event:StorageEvent)=>{if(event.key===JOURNAL_KEY||event.key===null)refresh();};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);},[]);
 useEffect(()=>{const changed=(event:StorageEvent)=>{if(mode!=='devnet'||event.key!=='nftlab-v1-devnet'||!event.newValue)return;try{const parsed=progressSchema.safeParse(JSON.parse(event.newValue));if(parsed.success)setProgress(parsed.data);}catch{}};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);},[mode]);
 const s=scenarios[selected];const record=progress.records[s.id];const count=completed(progress);
 const receiptProgram=process.env.NEXT_PUBLIC_ANCHOR_PROGRAM_ID;
 const receiptRecorded=!!receiptProgram&&progress.receipt?.programId===receiptProgram&&progress.receipt?.wallet===wallet.publicKey?.toBase58();
 useEffect(()=>{let cancelled=false;const gen=++generation.current;setReady(false);setSelected(0);setAnswers([]);setQuizResult(null);setMessage('');setRecipient('');let local=freshProgress();let hasLocal=false;
 try{const raw=localStorage.getItem(`nftlab-v1-${mode}`);if(raw){const parsed=progressSchema.safeParse(JSON.parse(raw));if(parsed.success){local=parsed.data;hasLocal=true;}}}catch{setMessage('ブラウザ保存を読み込めませんでした。');}
 setProgress(local);
 fetch(`/api/progress?namespace=${mode}`).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{if(cancelled||generation.current!==gen)return;if(!hasLocal&&data.progress){const parsed=progressSchema.safeParse(data.progress);if(parsed.success)setProgress(parsed.data);}setStorage(data.storage==='postgres'?'PostgreSQLに同期':'ブラウザに保存');}).catch(()=>{if(!cancelled)setStorage('ブラウザのみ保存・同期停止');}).finally(()=>{if(!cancelled)setReady(true);});return()=>{cancelled=true;};
 },[mode]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(`nftlab-v1-${mode}`,JSON.stringify(progress));}catch{setStorage('ブラウザ保存失敗');}const abort=new AbortController();const timer=setTimeout(()=>{fetch(`/api/progress?namespace=${mode}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(progress),signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>setStorage(d.storage==='postgres'?'PostgreSQLに同期':'ブラウザに保存')).catch(e=>{if(e.name!=='AbortError')setStorage('ブラウザのみ保存・同期停止');});},350);return()=>{clearTimeout(timer);abort.abort();};},[progress,ready,mode]);
 function select(i:number){if(busy)return;setSelected(i);setAnswers([]);setQuizResult(null);setRecipient('');setMessage('');}
 function quiz(){const passed=passQuiz(s.id,answers);setQuizResult(passed);if(passed){const next=advance(progress,s.id,'unlock');if(mode==='devnet'){try{localStorage.setItem('nftlab-v1-devnet',JSON.stringify(next));}catch{setStorage('ブラウザ保存失敗');}}setProgress(next);setMessage('クイズ合格！サンドボックスを解放しました。');}else setMessage('解説を確認して、もう一度挑戦しましょう。');}
 function snapshot():Progress{const raw=localStorage.getItem('nftlab-v1-devnet');if(!raw)return progress;const parsed=progressSchema.safeParse(JSON.parse(raw));if(!parsed.success)throw new Error('学習記録を読み取れません。取引を停止しました。');return parsed.data;}
 async function runChain(scope:PendingTransaction['scope'],kind:PendingTransaction['action'],run:(observe:TransactionObserver)=>Promise<unknown>){
  if(readPending(localStorage))throw new Error('確認待ちの取引があります。先に取引状況を再確認してください。');
  const before=snapshot();if(scope==='certificate'){if(completed(before)!==3||(kind==='mint'&&before.certificate))throw new Error('修了証の学習記録が更新されています。画面を開き直してください。');if(kind==='receipt'&&before.receipt?.programId===receiptProgram&&before.receipt?.wallet===wallet.publicKey?.toBase58())throw new Error('このウォレットの学習完了は記録済みです。');}else {if(kind==='receipt')throw new Error('操作が正しくありません。');if(kind!=='mint'&&before.records[scope].asset!==progress.records[scope].asset)throw new Error('別のタブでNFTが更新されています。画面を開き直してください。');advance(before,scope,kind);}
  let saved:PendingTransaction|null=null;
  await run(data=>{const transaction:PendingTransaction={...data,...(kind==='receipt'?{programId:receiptProgram}:{}),version:1,id:crypto.randomUUID(),scope,action:kind,before,createdAt:new Date().toISOString()};savePending(localStorage,transaction);saved=transaction;setPending(transaction);});
  if(!saved)throw new Error('取引の保存内容を確認できません。');
  const next=commitConfirmed(localStorage,snapshot(),saved);setProgress(next);setPending(null);
 }
 async function action(kind:'mint'|'transfer'|'redeem'){
  if(operation.current||chainBlocked)return;operation.current=true;setBusy(true);setMessage('');
  try{if(mode==='devnet')await withTransactionLock(async()=>{
   const chain=await import('@/lib/devnet');const origin=process.env.NEXT_PUBLIC_APP_URL||window.location.origin;
   await runChain(s.id,kind,observe=>kind==='mint'?chain.mintNft(endpoint,wallet,`NFTLab ${s.title}`,`${origin}/api/metadata/${s.id}`,observe):kind==='transfer'?chain.transferNft(endpoint,wallet,record.asset!,recipient.trim(),observe):chain.redeemNft(endpoint,wallet,record.asset!,observe));
  });else {const details=kind==='mint'?{asset:`SIM-${crypto.randomUUID()}`,owner:'あなた'}:{owner:'練習パートナー'};setProgress(p=>advance(p,s.id,kind,details));}
  setMessage(kind==='redeem'?'利用を確認しました。このシナリオは完了です。':kind==='transfer'?'所有者が変わりました。次は利用の確認です。':'NFTを発行しました。次は譲渡を体験しましょう。');
  }catch(e){setMessage(e instanceof Error?e.message:'操作に失敗しました。');}finally{operation.current=false;setBusy(false);}
 }
 async function certificate(){
  if(operation.current||chainBlocked||count!==3||progress.certificate)return;operation.current=true;setBusy(true);setMessage('');
  try{if(mode==='devnet')await withTransactionLock(async()=>{
   if(receiptProgram&&!receiptRecorded){const {recordReceipt}=await import('@/lib/anchor-receipt');await runChain('certificate','receipt',observe=>recordReceipt(endpoint,wallet,receiptProgram,observe));}
   const {mintNft}=await import('@/lib/devnet');const origin=process.env.NEXT_PUBLIC_APP_URL||window.location.origin;
   await runChain('certificate','mint',observe=>mintNft(endpoint,wallet,'NFTLab Sim completion certificate',`${origin}/api/metadata/certificate`,observe));
  });else setProgress(p=>({...p,certificate:{id:`SIM-CERT-${crypto.randomUUID()}`,date:new Date().toISOString()}}));
  setMessage('修了証を発行しました。');
  }catch(e){setMessage(e instanceof Error?e.message:'修了証の発行に失敗しました。');}finally{operation.current=false;setBusy(false);}
 }
 async function recordCompletion(){
  if(mode!=='devnet'||!receiptProgram||!wallet.connected||operation.current||chainBlocked||count!==3||receiptRecorded)return;operation.current=true;setBusy(true);setMessage('');
  try{await withTransactionLock(async()=>{const {recordReceipt}=await import('@/lib/anchor-receipt');await runChain('certificate','receipt',observe=>recordReceipt(endpoint,wallet,receiptProgram,observe));});setMessage('接続ウォレットに学習完了を記録しました。');}
  catch(e){setMessage(e instanceof Error?e.message:'学習完了の記録に失敗しました。');}finally{operation.current=false;setBusy(false);}
 }
 async function recover(){
  if(operation.current)return;operation.current=true;setBusy(true);setMessage('');
  try{await withTransactionLock(async()=>{
   const transaction=readPending(localStorage);if(!transaction){setPending(null);return;}
   const {recoverTransaction}=await import('@/lib/transaction-recovery');const result=await recoverTransaction(endpoint,transaction);
   if(result.state==='confirmed'){const next=commitConfirmed(localStorage,snapshot(),transaction);setProgress(next);setPending(null);setMessage('取引の成功を確認し、学習記録を復旧しました。');}
   else if(result.state==='failed'){clearPending(localStorage,transaction.id);setPending(null);setMessage('取引の失敗を確認しました。学習進捗は変更していません。内容を確認して再試行できます。');}
   else setMessage(result.expired?'取引の有効期限は過ぎていますが、成功・失敗を確認できません。重複を防ぐため記録を保持しています。Explorerまたは履歴を取得できるDevnet RPCで確認してください。':'取引をまだ確認できません。新しく発行せず、しばらくしてから再確認してください。');
  });}catch(e){setMessage(e instanceof Error?e.message:'取引を確認できません。記録を保持しています。');}finally{operation.current=false;setBusy(false);}
 }
 async function share(){if(!progress.certificate)return;const text=`NFTLab Simで3つのNFT体験を完了しました！${mode==='demo'?'練習モードの修了証':'Devnet NFT'}: ${progress.certificate.id}`;try{if(navigator.share)await navigator.share({title:'NFTLab Sim',text});else{await navigator.clipboard.writeText(text);setMessage('修了証の情報をコピーしました。');}}catch{setMessage('共有できませんでした。修了証IDをコピーして共有できます。');}}
 function reset(){if(busy||chainBlocked||!window.confirm('このモードの学習進捗をリセットしますか？Devnet上のNFTは削除されません。'))return;setProgress(freshProgress());select(0);}
 return <main>
 <header><a className="brand" href="/" aria-label="NFTLab Sim ホーム"><span className="brand-icon">⬡</span><strong>NFTLab <span>Sim</span></strong></a><div className="header-tools"><span className="network"><i/> {mode==='demo'?'SIMULATION':'SOLANA DEVNET'}</span>{mode==='devnet'&&<WalletButton>{wallet.connecting?'接続中…':wallet.disconnecting?'切断中…':wallet.connected&&wallet.publicKey?`${wallet.wallet?.adapter.name ?? 'Wallet'} · ${wallet.publicKey.toBase58().slice(0,4)}…${wallet.publicKey.toBase58().slice(-4)}`:wallet.wallet?`${wallet.wallet.adapter.name}を接続`:'ウォレットを選択'}</WalletButton>}</div></header>
 <section className="hero"><div><p className="eyebrow">THE NFT PRACTICE LAB</p><h1>知るだけから、<br/><em>使える</em>へ。</h1><p className="hero-copy">クイズで学び、NFTを発行・譲渡・利用する。<br/>実際の資産を使う前に、小さな実践を重ねよう。</p><div className="mode-toggle" aria-label="体験モード"><button disabled={busy} aria-pressed={mode==='demo'} onClick={()=>setMode('demo')}>練習モード</button><button disabled={busy} aria-pressed={mode==='devnet'} onClick={()=>setMode('devnet')}>Devnetで体験 ↗</button></div><p className="mode-note">{mode==='demo'?'ウォレット不要・手数料なし。NFT操作はブラウザ内のシミュレーションです。':'実際のDevnet NFTを操作します。テストSOLが必要です。Mainnetは使用しません。'}</p></div><div className="hero-art" aria-hidden="true"><div className="orb">◈</div><span className="art-caption">LEARN. MINT. TRANSFER. REDEEM.</span><span className="art-tag">SANDBOX / 001</span></div></section>
 {mode==='devnet'&&<DevnetWalletStatus endpoint={endpoint}/>}
 {mode==='devnet'&&(pending||journalError)&&<section className="pending-transaction" aria-label="確認待ち取引"><h2>確認待ちの取引があります</h2>{pending?<><p>同じ署名から状況を確認します。確認が終わるまで、新しい取引と進捗リセットを停止しています。</p><p className="address">署名: {pending.signature}</p><a href={`https://explorer.solana.com/tx/${pending.signature}?cluster=devnet`} target="_blank" rel="noreferrer">Explorerで取引を確認 ↗</a><button className="primary" disabled={busy||!ready} onClick={recover}>取引状況を再確認</button></>:<p>{journalError}</p>}</section>}
 <section className="progress-bar"><div><span className="eyebrow">YOUR LEARNING JOURNEY</span><h2>3つの体験で、仕組みをつかむ</h2></div><div className="progress-detail"><strong>{count}<span> / 3 完了</span></strong><progress value={count} max={3}/><small>{storage}</small></div></section>
 <div className="workspace"><nav className="scenario-list" aria-label="シナリオ">{scenarios.map((item,i)=><button key={item.id} disabled={!ready||busy||!canOpen(progress,i)} onClick={()=>select(i)} className={`scenario-card ${i===selected?'active':''}`} aria-current={i===selected?'step':undefined}><div className="card-top"><span className="scenario-icon">{item.icon}</span><span className="number">{item.number}</span></div><small>{item.subtitle}</small><h3>{item.title}</h3><p>{item.description}</p><div className="card-status">{!canOpen(progress,i)?'前の体験を完了して解放':stages[progress.records[item.id].stage]} <span>{progress.records[item.id].stage==='redeemed'?'✓':'→'}</span></div></button>)}</nav>
 <section className="lab-panel" aria-busy={busy}><div className="panel-heading"><div><p className="eyebrow">SCENARIO {s.number} / {mode==='demo'?'SIMULATION':'DEVNET'}</p><h2>{s.title}</h2></div><span className="pill">{stages[record.stage]}</span></div><p className="lesson">{s.lesson}</p>
 {record.stage==='locked'?<div className="quiz"><h3>まず、2問のチェック</h3>{s.questions.map((q,qi)=><fieldset key={q.prompt}><legend>{qi+1}. {q.prompt}</legend>{q.options.map((option,oi)=><label key={option} className={answers[qi]===oi?'chosen':''}><input type="radio" name={`question-${s.id}-${qi}`} checked={answers[qi]===oi} onChange={()=>{setAnswers(a=>{const copy=[...a];copy[qi]=oi;return copy;});setQuizResult(null);}}/>{option}</label>)}{quizResult===false&&<p className="explanation">{answers[qi]===q.answer?'✓':'↳'} {q.explanation}</p>}</fieldset>)}<button className="primary" onClick={quiz} disabled={chainBlocked||!ready||s.questions.some((_,i)=>answers[i]===undefined)}>回答して体験を解放 →</button></div>:<div className="sandbox"><div className="nft-preview"><div className="nft-top"><span>DEMO NFT</span><span>{mode==='demo'?'SIM':'DEVNET'}</span></div><div className="nft-symbol">{s.icon}</div><h3>{s.reward}</h3><p>{record.stage==='ready'?'NOT MINTED':record.stage==='redeemed'?'REDEEMED / USED':'ACTIVE ASSET'}</p></div><div className="actions"><ol className="steps"><li className={record.stage!=='ready'?'done':''}>01 発行する</li><li className={['transferred','redeemed'].includes(record.stage)?'done':''}>02 譲渡する</li><li className={record.stage==='redeemed'?'done':''}>03 利用する</li></ol><p>{record.stage==='ready'?'NFTを発行し、あなたが最初の所有者になります。':record.stage==='minted'?'譲渡すると、次の持ち主へ利用権が移ります。':record.stage==='transferred'?'現在の所有者が利用します。この教材ではNFTを消費して二重使用を防ぎます。':'発行から利用までの流れを体験しました。'}</p>{record.owner&&<p className="address">所有者: {record.owner}</p>}{record.asset&&<p className="address">NFT: {record.asset}</p>}{mode==='devnet'&&record.stage==='minted'&&<label className="recipient">譲渡先のDevnetアドレス<input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="別の練習用ウォレット"/></label>}{mode==='devnet'&&record.stage==='transferred'&&<p className="hint">譲渡先のウォレットを接続して利用してください。同じブラウザの進捗を使います。返送して元のウォレットで利用することもできます。</p>}{record.signature&&<a className="tx" href={`https://explorer.solana.com/tx/${record.signature}?cluster=devnet`} target="_blank" rel="noreferrer">トランザクションを確認 ↗</a>}{record.stage==='ready'&&<button className="primary" disabled={chainBlocked||busy||!ready||(mode==='devnet'&&!wallet.connected)} onClick={()=>action('mint')}>NFTを発行する →</button>}{record.stage==='minted'&&<button className="primary" disabled={chainBlocked||busy||(mode==='devnet'&&(!wallet.connected||!recipient.trim()))} onClick={()=>action('transfer')}>NFTを譲渡する →</button>}{record.stage==='transferred'&&<button className="primary" disabled={chainBlocked||busy||(mode==='devnet'&&!wallet.connected)} onClick={()=>action('redeem')}>NFTを利用・消費する →</button>}{record.stage==='redeemed'&&selected<2&&<button className="primary" onClick={()=>select(selected+1)}>次のシナリオへ →</button>}{busy&&<p role="status">承認・確認を待っています。画面を閉じずにお待ちください。</p>}{mode==='devnet'&&!wallet.connected&&<p className="hint">右上のボタンからウォレットを接続してください。</p>}</div></div>}
 <p className="notice" role="status" aria-live="polite">{message}</p></section></div>
 <section className={`certificate ${count===3?'unlocked':''}`}><div className="certificate-icon">✧</div><div><p className="eyebrow">YOUR PROOF OF PRACTICE</p><h2>小さな実践を、修了証に。</h2><p>{progress.certificate?'修了証を発行しました。学んだことを共有しましょう。':'3つのシナリオを完了すると、修了証を発行できます。'}</p><small>{mode==='demo'?'練習モードではブラウザ内のデジタル修了証です。':'DevnetではMetaplex Core NFTとして発行します。'} 自己申告の学習記録であり、公的資格・認証ではありません。</small>{progress.certificate&&<p className="address">{progress.certificate.id}</p>}{progress.certificate?.signature&&<a href={`https://explorer.solana.com/address/${progress.certificate.id}?cluster=devnet`} target="_blank" rel="noreferrer">修了証NFTを確認 ↗</a>}</div><button className="primary" disabled={chainBlocked||busy||!ready||count<3||(mode==='devnet'&&!wallet.connected)} onClick={progress.certificate?share:certificate}>{progress.certificate?'修了証を共有 ↗':count<3?`あと${3-count}つで解放`:'修了証を発行 →'}</button></section>
 {mode==='devnet'&&(receiptProgram||progress.receipt)&&<section className="learning-receipt" aria-label="チェーンの学習記録"><div><h2>学習完了をDevnetに記録</h2><p>3つの体験を完了したことを、接続ウォレットの自己申告として記録します。発行済みの修了証からも追加できます。</p>{progress.receipt&&<><p>学習完了を記録済みです。</p><p className="address">記録したウォレット: {progress.receipt.wallet}</p><a href={`https://explorer.solana.com/address/${progress.receipt.id}?cluster=devnet`} target="_blank" rel="noreferrer">学習記録を確認 ↗</a><a href={`https://explorer.solana.com/tx/${progress.receipt.signature}?cluster=devnet`} target="_blank" rel="noreferrer">記録の取引を確認 ↗</a></>}{receiptProgram&&!wallet.connected&&<p className="hint">右上からウォレットを接続してください。</p>}</div>{receiptProgram&&<button className="primary" disabled={chainBlocked||busy||!ready||count!==3||!wallet.connected||receiptRecorded} onClick={recordCompletion}>{receiptRecorded?'このウォレットに記録済み':count<3?`あと${3-count}つで記録`:'学習完了を記録 →'}</button>}{busy&&<p role="status">承認・確認を待っています。</p>}</section>}
 <footer><span>NFTLab Sim · Practice before you leap.</span><button onClick={reset} disabled={chainBlocked||!ready||busy}>学習をリセット</button><a href="https://github.com/haruharuoharu/nftlab-sim" target="_blank" rel="noreferrer">GitHub ↗</a></footer>
 </main>;
}
